### ISSUE TITLE
Font icon page

### ISSUE THREAD

**Issue by Mukhammadali** [pratikborsadiya/vali-admin#1]
**Issue description**
Font icon page is not showing up and throwing error. I think you guys have to check that out. My device is Android galaxy s5. 

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by Mukhammadali** [comment]
It is saying that there is kind of security problem with your site certificate

**Comment by pratikborsadiya** [comment]
@Mukhammadali Thanks for pointing it out. It's fixed now.
