### ISSUE TITLE
change theme

### ISSUE THREAD

**Issue by hinditutorpoint** [pratikborsadiya/vali-admin#105]
hi sir thank for this template 
i have one question how to change theme color

**Comment by larmdcm** [comment]
you can download the source code.
in src/sass/1-tools/_vars.scss edit your own theme color.
Then rebuild it using npm.

**Comment by miguemm** [comment]
Hi, love this theme but im new in this
Can you recommend me a video of how to rebuild it using npm as you say in order to change color ? pls

**Comment by pratikborsadiya** [comment]
If you're new to the web development, find and replace the primary color to the new color in `main.css`. This is the easiest option to change the color theme.
