### ISSUE TITLE
Add component modal bootstrap example

### ISSUE THREAD

**Issue by henriquek3** [pratikborsadiya/vali-admin#11]
**Issue description**
I would like to request some examples of implementing bootstrap modals on the Bootstrap Elements page

**Comment by pratikborsadiya** [comment]
@henriquek3 Hi Jean Freitas,
You will find examples about implementing bootstrap modals [here](https://getbootstrap.com/docs/3.3/javascript/#modals). If you want themed modal windows, I request you to wait for some time, as I am busy in transitioning theme to Bootstrap 4. I will include those examples in next next release of the theme. Please keep an eye on [this branch](https://github.com/pratikborsadiya/vali-admin/tree/bootstrap-v4) for updates.

**Comment by henriquek3** [comment]
Thanks, this helps me a lot. I'll wait for the bootstrap-v4 branch.

**Comment by pratikborsadiya** [comment]
Hi Jean Freitas,
As I promised an example of bootstrap modal is present on this [page](http://pratikborsadiya.in/vali-admin/bootstrap-components.html) as version 2.0 is out.

**Comment by henriquek3** [comment]
Olá Pratik, bom dia e feliz ano novo! Muito obrigado por me avisar sobre o exemplo!


________________________________
De: Pratik Borsadiya <notifications@github.com>
Enviado: domingo, 31 de dezembro de 2017 18:16
Para: pratikborsadiya/vali-admin
Cc: Jean Freitas; State change
Assunto: Re: [pratikborsadiya/vali-admin] Add component modal bootstrap example (#11)


Hi Jean Freitas,
As I promised an example of bootstrap modal is present on this page<http://pratikborsadiya.in/vali-admin/bootstrap-components.html> as version 2.0 is out.
