### ISSUE TITLE
Chart not fully covered the card when i click on the sidebar toggle

### ISSUE THREAD

**Issue by riyazahmad97** [pratikborsadiya/vali-admin#115]
When i click on the sidebar toggle icon in charts.html, all of the graph are not fully covering the card (some blank space in the right of the card). I have try to amend some css to it but still it is not covering the card. Are there any possible ways to make the chart fully covering the card when I click on the sidebar toggle button?

**Comment by pratikborsadiya** [comment]
Fixed in v4.1.0
