### ISSUE TITLE
Transition to Bootstrap 4

### ISSUE THREAD

**Issue by pratikborsadiya** [pratikborsadiya/vali-admin#12]
Transition to Bootstrap 4 is in progress. Please keep an eye on [this branch](https://github.com/pratikborsadiya/vali-admin/tree/bootstrap-v4) for updates.

**Comment by pratikborsadiya** [comment]
Next version 2.0 is scheduled to be released on 1st January,2018 with Bootstrap 4, and lot's of improvements and fixes. Stay tuned!

**Comment by AGhasemzadeh** [comment]
Thanks.
I like admin like this.

**Comment by pratikborsadiya** [comment]
Version 2.0 is [here](https://github.com/pratikborsadiya/vali-admin/releases/tag/v2.0.0) :fireworks:
