### ISSUE TITLE
Many small bugs

### ISSUE THREAD

**Issue by neznaika0** [pratikborsadiya/vali-admin#124]
**Describe the bug**
1. The menu in the sidebar (collapsed) has a space between the list
2. The chart is too big than the card
3. I don't know if this is intended, or just an omission: When the sidebar is collapsed, clicking on the menu title (Tables, Forms, UI) opens the tree, BUT in hidden mode. If you expand the sidebar the tree will be expanded
4. There is a partial animation of the slide switching on the user's page: There is an animation for settings, when you click back on the Timeline - a hard display
5. The sidebar does not remember its collapse or open state. I think it can be done by default for a long time
6. Widgets on the medium and small screen are not displayed correctly - they go beyond the blocks. It is enough to reduce the browser window to see

**To Reproduce**
1. Go to demo pages
https://pratikborsadiya.in/vali-admin/dashboard.html
https://pratikborsadiya.in/vali-admin/page-user.html
https://pratikborsadiya.in/vali-admin/widgets.html
5. Click and see error

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome

**Additional context**
sorry for a few mistakes in one "issue", but I don't see the point in immediately reporting 6 separate ones.

![vali1](https://github.com/pratikborsadiya/vali-admin/assets/17183530/b4534fc4-0b2d-4eb5-8a9e-bf4fdd45b744)
![vali2](https://github.com/pratikborsadiya/vali-admin/assets/17183530/5ac13ad6-31a7-4189-9361-f407e71cd10c)

**Comment by pratikborsadiya** [comment]
Fixed in v4.1.0
