### ISSUE TITLE
How can I download Bootstrap 4 version?

### ISSUE THREAD

**Issue by AGhasemzadeh** [pratikborsadiya/vali-admin#15]
Hello,
Where can I download Bootstrap version 4?

**Comment by AGhasemzadeh** [comment]
Please add beta version in npm.

**Comment by pratikborsadiya** [comment]
Hi Ali,

Bootstrap 4 version is scheduled to be released on 1st Jan 2018, Which is 4 days from today. You can get it from  [this branch](https://github.com/pratikborsadiya/vali-admin/tree/bootstrap-v4).

**Comment by AGhasemzadeh** [comment]
We can test beta version before release.
