### ISSUE TITLE
Website + Admin page.

### ISSUE THREAD

**Issue by AGhasemzadeh** [pratikborsadiya/vali-admin#16]
Hello,
I think it would be good idea that we have simple website page.
for example https://wrapbootstrap.com/theme/smarty-website-admin-rtl-WB02DSN1B has both website and admin.

**Comment by pratikborsadiya** [comment]
Hi Ali,
Thanks  for the suggestion. Unfortunately at this point I do not have time to create and maintain a website along with the admin theme as I have a full time Job. If you want to contribute a pull request is always welcome.
