### ISSUE TITLE
Dark font (Need to be sharp)

### ISSUE THREAD

**Issue by AGhasemzadeh** [pratikborsadiya/vali-admin#17]
**Issue description**
Fonts in notifications are dark and not sharp like others.
![dark fonts](https://user-images.githubusercontent.com/26847446/34349761-5c583380-ea28-11e7-9abf-7b6ec42c0670.jpg)

**Comment by pratikborsadiya** [comment]
Hi Ali,

Thanks for pointing out.
The font color is the same as body font color which is an expected behaviour not a bug.
