### ISSUE TITLE
Bootstrap Modal

### ISSUE THREAD

**Issue by guischafer** [pratikborsadiya/vali-admin#26]
**Issue description**

When I tried to create a bootstrap modal, it didn't work. When this template was with bootstrap 3 it worked like a charm, now it doesn't. Tried to fix it myself, but failed. 

I've faced problems with the modal code from bootstrap 4 docs and using the modal code presented in the bootstrap elements page - triggered by jquery .modal('show') -, both presented the same type of errors.

  * The modal opacity is equal to the rest of the page
  * The modal stay underneath the navbar
  * Can't dismiss

**Comment by pratikborsadiya** [comment]
Hi @guischafer ,

Fixed the issue just for you. :smile:
