### ISSUE TITLE
Font Awesome Include ? (question)

### ISSUE THREAD

**Issue by andreabenini** [pratikborsadiya/vali-admin#27]
Hi Pratik,
I have just downloaded your awesome template and even if I have never used pug it seems it's quite easy to use and learn. I have a question about external libs or "compiled/raw" files.
on _head.pug you're using font-awesome ('cause bootstrap needs them) so you're taking them from classic CDN url (https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css).
What should I do if I don't want to rely on that site ? Is it possible for me to include minified files (or whatever i need to add) somewhere so they're compiled/copied in the docs dir during generation ?
I just need a dir where I can copy them in order to keep original content and having them copied during the build process

btw: you're doing a really good job with it

Thanks in advance
Ben

**Comment by pratikborsadiya** [comment]
Hi Ben,

Follow this steps to include FontAwesome locally without using CDN.

 - Clone FontAwesome [GitHub repo](https://github.com/FortAwesome/Font-Awesome)
 - Create folders named `font-awesome` in `src/sass/1-tools` and `fonts` in `docs`
 - Copy all the files inside `scss` folder from cloned FontAwesome repo to newly created folder `src/sass/1-tools/font-awesome`
  - Copy all the files inside `fonts` to newly created folder `docs/fonts`
  - Finally import the scss file by adding following code in your `src/sass/main.scss` file on line number 14 `@import '1-tools/font-awesome/font-awesome'`
  - Run `npm run build` command to build css file from sass files
  -  Remove CDN Referancec from `_head.pug`

Please let me know whether this solved you problem or not. 

If you liked the theme, Do star and share it. :smile:

**Comment by andreabenini** [comment]
Hi Pratik,
I have just followed your hints and everything works fine, your suggestions were really useful, I'm still looking at possible side effects but seems to be perfect.
Cloned your repo and picked up suggested files from Font-Awesome, the project is on my github repo so if you want to take it back as a common pull request let me know

Excellent job
Ben
