### ISSUE TITLE
Login page Textbox does not working on Safari 

### ISSUE THREAD

**Issue by CharnjeetIotasol** [pratikborsadiya/vali-admin#3]
**Issue description**
I am try to access design on safari it not working. Input text box does not write able.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by pratikborsadiya** [comment]
@CharnjeetIotasol This issue is fixed in commit be7875a9a0a7d54841ad3a2e1df55e7d4abbca77. Make sure that you are running latest code. If the issue still persists please provide more details like which safari version you are using.
