### ISSUE TITLE
Make app-title Fixed 

### ISSUE THREAD

**Issue by Cali03** [pratikborsadiya/vali-admin#30]
**Issue description**
Well, it's not really an issue but an improvement. Would it be possible to make the app-title stay fixed when scrolling down?

**Steps to reproduce (if you knew)**
Go into the charts page for example and scrolldown then you can see the app-title is gone.

**Expected behaviour**
app-title stay fixed when scroll down.

**Other Note (feature-request, question, etc...)**

**Comment by pratikborsadiya** [comment]
Hi @Cali03 ,

I Don't think making app-title fixed is a good idea. As you have top header sticky, having too much sticky content is an usability issue on screens with less vertical space.

If you still want to make it sticky add the following coded in your ```.app-title``` class
```css
.app-title {
    ...
    position: sticky;
    top: 50px;
    z-index: 3;
}
```
