### ISSUE TITLE
SideBar Extends when its toggled

### ISSUE THREAD

**Issue by Cali03** [pratikborsadiya/vali-admin#31]
Issue description
If you have the sidebar toggled and you reduce the page there comes a time when the sidebar is extended.

Steps to reproduce (if you knew)
Toggled the sidebar and reduce the page or toggled the sidebar and with change resolution to mobile.

Expected behaviour
Sidebar stay toggled

Other Note (feature-request, question, etc...)

**Comment by pratikborsadiya** [comment]
Hi @Cali03 ,

Reducing page width is something that only happens while developing. It's not something a normal user would do.
