### ISSUE TITLE
sidebar is not visible and content not fit on a samsung galaxy tab s2

### ISSUE THREAD

**Issue by roadavid** [pratikborsadiya/vali-admin#32]
**Issue description**
I tested on Firefox 58.0.1 and Chrome Version 63.0.3239.111

**Steps to reproduce (if you knew)**

1.- Open a web browser on a Galaxy Tab S2.
2.- Go to http://pratikborsadiya.in/vali-admin/ 

**Expected behaviour**
Content fit and siderbar visible

**Other Note (feature-request, question, etc...)**

![screenshot_20180209-113054](https://user-images.githubusercontent.com/11315636/36041086-1ead36f6-0d8d-11e8-941b-5be13f0093e6.png)

**Comment by pratikborsadiya** [comment]
Hi @roadavid ,

Please let me know your screen resolution. You can find it out by visiting this site https://www.whatismyscreenresolution.com

**Comment by pratikborsadiya** [comment]
Closing as there is no feedback from the reporter. If anybody else is facing the same issue feel free to reopen this issue.

**Comment by Cali03** [comment]
Hi @pratikborsadiya, 

Try with this screen resolution 768x1024.

Thanks

**Comment by roadavid** [comment]
Hi @pratikborsadiya , thanks for response, sorry by late answer. Screen resolution is 768x1024 like @Cali03 commented. Thanks in advance
![screenshot_20180319-095042](https://user-images.githubusercontent.com/11315636/37602789-c438122a-2b52-11e8-84ea-db8fc7dffe6b.png)
