### ISSUE TITLE
Fullcalendar error at initialization

### ISSUE THREAD

**Issue by Manuel512** [pratikborsadiya/vali-admin#34]
Good afternon, How are you today?
I come here with a problem using your beautiful theme, when I include all the required for the fullcalendar to work and initialize it, it shows me an error of **Cannot read property 'each' of null jquery-3.3.1.js:3827 **

![image](https://user-images.githubusercontent.com/8979657/36172882-a1555af4-10dd-11e8-8aa9-bef5d41af77c.png)

I just use the guide for trying it out, like this

`<div id="EventCalendar"></div>`
and initialize it with

`$("#EventCalendar").fullCalendar();`

It creates the calendar but, doesn't render the data because of that error, and I cant find a solution for it.
I really would like to use it with your theme, Good work btw

I even try lower the jquery version as mentioned in some posts of stackoverflow, but no such luck

It renders the calendar but is missing some complements like the title, and on and on.
![image](https://user-images.githubusercontent.com/8979657/36173045-36a6e1e0-10de-11e8-98e0-1fca163b57dd.png)

**Comment by pratikborsadiya** [comment]
Hi @Manuel512 

This seems to be an error in FullCalendar plugin or the way you pass the data to it. Please take a look at the FullCalendar docs [here](https://fullcalendar.io/docs/) and make sure that you are implementing it correctly. For your referance the fullcalendar version used in this theme is v2.5.0.
