### ISSUE TITLE
Linking to wrong version of fontawesome icons

### ISSUE THREAD

**Issue by jonaslagoni** [pratikborsadiya/vali-admin#37]
**Issue description**
Link to fontawesome icons is not the correct version which can confuse people.

**Other Note (feature-request, question, etc...)**
Added the correct link in fork project : https://github.com/jonaslagoni/vali-admin/commit/2df326b53d787d67ad8bd161612de34d6b87b32f

**Comment by pratikborsadiya** [comment]
Hi Jonas,
I have merged your changes into the official Repo. Thanks for your contribution.
