### ISSUE TITLE
How to remove animation on IE11

### ISSUE THREAD

**Issue by qeuyee** [pratikborsadiya/vali-admin#4]
**Issue description**
vali-admin is pretty,but i want to remove animation for IE11,don't need the animation in IE11.what should i do?thanks!

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by pratikborsadiya** [comment]
@qeuyee Will you please explain what animation you want to remove in IE11 and why?

**Comment by qeuyee** [comment]
When the page is switched, I think this is a poor user experience. other browsers are normal,such as chrome and FF and so on.

**Comment by pratikborsadiya** [comment]
@qeuyee I still am not able to understand which animation you are talking about. There is no animation appiled when you navigate the page. Can you please share the video-clip or GIF of the animated behaviour?

**Comment by qeuyee** [comment]
@pratikborsadiya 
![1234](https://user-images.githubusercontent.com/31116292/30240099-a4b51002-959c-11e7-9f66-bcf686f018b3.gif)

**Comment by qeuyee** [comment]
When I click the left menu,the menus slide in from the left.

**Comment by pratikborsadiya** [comment]
@qeuyee 
![video](https://user-images.githubusercontent.com/7806891/30279165-4f59fdc2-96c1-11e7-9021-3a5a94ea87a3.gif)

I am using IE11 on windows 10 and it's working fine. However it seems to be the bug with older versions of IE11. Here is a post that can be helpful. [Link](https://css-tricks.com/transitions-only-after-page-load/)
