### ISSUE TITLE
Include fonts locally for offline app

### ISSUE THREAD

**Issue by kabeza** [pratikborsadiya/vali-admin#40]
**Issue description**
Is there a way to download fonts and load them locally? My app wont have Internet connection, therefore it wont be able to load (css) the Google Fonts from the CDN

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

How should I do to download the fonts and modify the css so I include them locally
Thanks

**Comment by pratikborsadiya** [comment]
Hi @kabeza 

Please follow this [guide](https://victorfont.com/use-google-fonts-locally/). 
If you like this theme consider giving it a star.

Thanks.
