### ISSUE TITLE
Change main color without compiling

### ISSUE THREAD

**Issue by kabeza** [pratikborsadiya/vali-admin#41]
**Issue description**
I don't have npm, node, etc. to compile saas nor css
Is there an easy way to change main color (for everything) in the compiled main.css file from static files (docs folder)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

Thanks

**Comment by pratikborsadiya** [comment]
Just find and replace all occurrences of the main color (#009688) with the color you want to use in main.css using your code editor.
