### ISSUE TITLE
Is there an upgrade plan for vali-admin ?

### ISSUE THREAD

**Issue by billchen198318** [pratikborsadiya/vali-admin#44]
Is there an upgrade plan for vali-admin ?

E.g update core to bootstrap v4.1.0/v4.1.1 or later.

Thanks.

**Comment by pratikborsadiya** [comment]
Update is coming soon. Stay Tuned.!

**Comment by billchen198318** [comment]
Thank you very much for your contribution to such a good product vali-admin, thanks.

**Comment by pratikborsadiya** [comment]
A new version 2.4.o is released today to update the bootstrap version to 4.1.1
