### ISSUE TITLE
To enable RTL support

### ISSUE THREAD

**Issue by muhanna5** [pratikborsadiya/vali-admin#48]
Can you explain in a simpler way

Uncomment this line @import '3-component/rtl'; in src/sass/main.scss.
Add dir="rtl" attribute to <html> tag in src/pug/layouts/_layout.pug.
Build the source files using npm run build command.

thanks

**Comment by pratikborsadiya** [comment]
Hi @muhanna5,

I think this steps are fairly self explanatory. Will you tell me precisely what are your expectations.

**Comment by alaa-jad** [comment]
hello, after doing the first two steps how to build with npm.
I didn't use npm before, I have npm command line but how to run build on the project, please advise.
thanks

**Comment by pratikborsadiya** [comment]
Follow [this](https://github.com/pratikborsadiya/vali-admin#getting-started) steps.

**Comment by alaa-jad** [comment]
Thank you
