### ISSUE TITLE
Maximum width as in Bootstrap

### ISSUE THREAD

**Issue by neznaika0** [pratikborsadiya/vali-admin#49]
**Issue description**

Hey. Is it possible to limit the total width with small blood? Like a container in a bootstrap. Very large blocks are obtained. This is very good for a lot of *.tile*, but for standard units it is unnecessary.

**Steps to reproduce (if you knew)**

- View on 4k monitor
- Enable Developer Tools and change screen size to 4k

**Comment by pratikborsadiya** [comment]
Hi @neznaika0 

I too have thought about this but this is a generic theme and the option you are suggesting varies case to case. So instead of implementing this in the theme itself I left it up to the implementer to restrict the width of container if they want to.
