### ISSUE TITLE
Issue on hovering mouse on the sidebar mini

### ISSUE THREAD

**Issue by KinLiverpool** [pratikborsadiya/vali-admin#5]
**Issue description**
I do want to automatically hide sidebar (displaying only icon) when loading the page I have been using on the blank page template. The issue I found was that it actually hided when I set <body class="sidebar-mini fixed"> to <body class="sidebar-mini sidebar-collapse fixed">. Unfortunately, it doesn't display sub menu when I hover mouse on such sub menu.  Could you please teach me how to automatically set hiding sidebar (displaying only icon) when loading the page?

**Expected behaviour**
I wanna see the hidden sub menu with only icons while loading the page and also display sub menu when I hover mouse on the icon.

Thank you very much indeed. I would appreciate for your answering.
Email : kinaorr@yahoo.com

**Comment by pratikborsadiya** [comment]
Add class `sidebar-collapse` to body element in order to display the icon menu by default.

**Comment by KinLiverpool** [comment]
I already added the mentioned tag. But, the first time the page loaded, it did not display sub menus while hovering on the icon. The way I tried was to click on Sidebar toggle button first. Then, it gets back normal.  Could you please give a resolution?

<body class="sidebar-mini fixed sidebar-collapse">

Thanks

**Comment by pratikborsadiya** [comment]
@KinLiverpool The issue is fixed.

**Comment by KinLiverpool** [comment]
Yeah this issue has been completely fixed. Thank you very much indeed. That's great work.

**Comment by pratikborsadiya** [comment]
@KinLiverpool I am happy that vali if of help to you.

**Comment by KinLiverpool** [comment]
It's very helpful because I'm poor in designing from scratch anyway. Apart of this, have you got any solutions?

**Comment by pratikborsadiya** [comment]
No I have not any other solutions at this time.

**Comment by KinLiverpool** [comment]
Thanks :)

**Comment by ajkhairnar-dev** [comment]
sidebar collapse not working in angular plz help...
