### ISSUE TITLE
Component versions

### ISSUE THREAD

**Issue by AqpA** [pratikborsadiya/vali-admin#53]
Hello,

Actually it's not a problem.
Can you write versions of the components?

Thanks.

**Comment by pratikborsadiya** [comment]
Hi @AqpA 

Which components in perticular are you talking about?

**Comment by AqpA** [comment]
Hi,
For example sweetalert. You have used an older version and do not have usage documents.
Thanks

**Comment by pratikborsadiya** [comment]
Hi @AqpA 

You can find related documentation by clicking docs button on demo page for every component. Regarding version numbers I think I will mention them as well in the respective cards.

![screenshot from 2018-06-12 13-44-56](https://user-images.githubusercontent.com/7806891/41278186-ddcb19b2-6e46-11e8-8ad4-4bcd15a0bcef.png)
