### ISSUE TITLE
multiple menu

### ISSUE THREAD

**Issue by Anthony199509** [pratikborsadiya/vali-admin#54]
Hello, vali-admin template Great! However, how to add multiple menu css? Please

**Comment by pratikborsadiya** [comment]
Hi @Anthony199509 

Will you please elaborate more about which menus are you talking about?

**Comment by pratikborsadiya** [comment]
Closing as there is no response from reporter. If you want the same feature or are facing the same issue feel free to open a new issue with proper description of the problem.
