### ISSUE TITLE
datatable server paging is error

### ISSUE THREAD

**Issue by wangyayong** [pratikborsadiya/vali-admin#55]
**Issue description**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by pratikborsadiya** [comment]
Hi @wangyayong 
Will you explain more about the issue you are facing?

**Comment by pratikborsadiya** [comment]
Please follow data table official documentation for datatable related errors. https://datatables.net/manual/server-side
