### ISSUE TITLE
Overall color matching

### ISSUE THREAD

**Issue by hsl313** [pratikborsadiya/vali-admin#56]
**Issue description**
Your GitHub shows several colors
How to modify it, please!

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by theshaun** [comment]
Hi @hsl313 

You can change the colours by adjusting the _vars.scss file and then recompiling the source code.

> src/sass/1-tools/_vars.scss

**Comment by pratikborsadiya** [comment]
For  more information refer to issue #50 and #41.
