### ISSUE TITLE
Customize

### ISSUE THREAD

**Issue by kernelmota** [pratikborsadiya/vali-admin#65]
Developers could facilitate the themed css file, sass and pug files are not intuitive to work with

**Comment by pratikborsadiya** [comment]
Please be more specific about the issue you are facing which can explain why sass and pug are not intuitive.

**Comment by kernelmota** [comment]
Good morning, Template Vali Admin is nice and light (small),

 but to customize the colors, you need to compile packages (SASS),

while other templates already allow this option in the configuration menu



________________________________
De: Pratik Borsadiya <notifications@github.com>
Enviado: segunda-feira, 24 de setembro de 2018 10:15
Para: pratikborsadiya/vali-admin
Cc: kernelmota; Author
Assunto: Re: [pratikborsadiya/vali-admin] Customize (#65)


Please be more specific about the issue you are facing which can explain why sass and pug are not intuitive.

**Comment by pratikborsadiya** [comment]
@kernelmota It's super easy to edit sass and change the theme. Just follow the [documentation](https://pratikborsadiya.in/blog/vali-admin/) to know more about the sass and compilation process. You can also refer issues #50 #56 and #41 to know more about changing the color without compiling the sass. I still recommend you to use sass to compile It's super easy and convenient once you follow the instructions mentioned in the [documentation](https://pratikborsadiya.in/blog/vali-admin/).

**Comment by kernelmota** [comment]
Desculpe minha ignorancia, mas nunca trabalhei com recuros npm. E sinceramente apesar da documentação do template mencionar os comandos de instalação/compilação dos pacotes sass, nao estou sabendo identificar o local correto proceder com estes comandos. Terai alguma possibilidade de disponibilizar o css referente a cada tema para download? Antecipadamente agradeço imensamente a atenção.


________________________________
De: Pratik Borsadiya <notifications@github.com>
Enviado: quarta-feira, 26 de setembro de 2018 05:43
Para: pratikborsadiya/vali-admin
Cc: kernelmota; Mention
Assunto: Re: [pratikborsadiya/vali-admin] Customize (#65)


@kernelmota<https://github.com/kernelmota> It's super easy to edit sass and change the theme. Just follow the documentation<https://pratikborsadiya.in/blog/vali-admin/> to know more about the sass and compilation process. You can also refer issues #50<https://github.com/pratikborsadiya/vali-admin/issues/50> #56<https://github.com/pratikborsadiya/vali-admin/issues/56> and #41<https://github.com/pratikborsadiya/vali-admin/issues/41> to know more about changing the color without compiling the sass. I still recommend you to use sass to compile It's super easy and convenient once you follow the instructions mentioned in the documentation<https://pratikborsadiya.in/blog/vali-admin/>.

**Comment by pratikborsadiya** [comment]
@kernelmota The correct location to run this commands is from the folder which you have downloaded and which contains source code folder `src`. You can also use find and replace method to edit primary color directly as mentioned in [this](https://github.com/pratikborsadiya/vali-admin/issues/41#issuecomment-374962977) comment.
