### ISSUE TITLE
Issue with datepicker plugin

### ISSUE THREAD

**Issue by johanvf84** [pratikborsadiya/vali-admin#66]
Hi.
I have a trouble when using the datepicker plugin.  This control isn't aligned with the input.

![2018-09-28 22_31_27-custom form elements - vali admin](https://user-images.githubusercontent.com/22357684/46240512-5c783200-c36e-11e8-904e-7dc0e91bda70.png)

I was using other plugin (https://gijgo.com/datepicker/example/bootstrap-4). It was my solution

**Comment by arbh89** [comment]
This problem was reported to the team of datepicker. see https://github.com/uxsolutions/bootstrap-datepicker/issues/1941

As suggested this can be fixed with the following script.

```javascript
// This wrapper fixes wrong placement of picker when container has margins.
    var originaldatepicker = $.fn.datepicker;
    
    $.fn.datepicker = function () {
        var result = originaldatepicker.apply(this, arguments);

        this.on('show', function (e) {
            var $target = $(this),
                $picker = $target.data('datepicker').picker,
                top;

            if ($picker.hasClass('datepicker-orient-top')) {
                top = $target.offset().top - $picker.outerHeight() - parseInt($picker.css('marginTop'));
            } else {
                top = $target.offset().top + $target.outerHeight() + parseInt($picker.css('marginTop'));
            }

            $picker.offset({top: top});
        });

        return result;
    }
