### ISSUE TITLE
Bug on select with [multiple] and option selected

### ISSUE THREAD

**Issue by fefno** [pratikborsadiya/vali-admin#68]
Using select `multiple` and a `selected` option, some elements are getting a strange transition, as you can see at this video: [http://sendvid.com/3mgj91mu](http://sendvid.com/3mgj91mu)

**Comment by wykings** [comment]
you can set width 100% at select2 option like
`
$('.demoSelect').select2({
	width: "100%",
});
`

**Comment by fefno** [comment]
The bug is not the width. The bug is the wierd transtion AFTER i set the selected item with attribute multiple.

**Comment by pratikborsadiya** [comment]
Select2 is not supported with the latest release.
