### ISSUE TITLE
Date time picker

### ISSUE THREAD

**Issue by sanekiran** [pratikborsadiya/vali-admin#7]
**Issue description**
Am using Ur pane, in this panel date picker is working.but I need date with time,hours with seconds.please help me

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by pratikborsadiya** [comment]
@sanekiran The datepicker provided with the theme is from an external repo which is provided by https://github.com/uxsolutions/bootstrap-datepicker and it's not possible to select time with the datepicker. I suggest you to use this datetimepicker instead https://eonasdan.github.io/bootstrap-datetimepicker/.
