### ISSUE TITLE
How to closed toggle sidebar ?

### ISSUE THREAD

**Issue by aufche** [pratikborsadiya/vali-admin#71]
Hello

I am used your work.  But I am want to set sidebar toggle default is closed. how to set it ?

thanks

**Comment by aufche** [comment]
Not like that @pratikborsadiya 

I mean like this

![screenshot capture - 2018-12-09 - 09-16-04](https://user-images.githubusercontent.com/5567866/49692682-21c31f00-fb93-11e8-8ded-3855c581d743.png)


thank you

**Comment by pratikborsadiya** [comment]
Then dont't remove the class `sidebar-mini` and add class `sidenav-toggled` to body.
