### ISSUE TITLE
Update to Latest Bootstrap 4.2

### ISSUE THREAD

**Issue by hxmcn** [pratikborsadiya/vali-admin#77]
Thanks for your great work that build such an excellent Admin Template!

Bootstrap 4.2.1 release for a while, can you update valid-admin to BS 4.2 please?
Or, can you separate vali-admin CSS code from bootstrap CSS, so that we can upgrade BS independently.

**Comment by pratikborsadiya** [comment]
Updated Botstrap to latest version in 3.0.0
