### ISSUE TITLE
DateTime picker

### ISSUE THREAD

**Issue by sanekiran** [pratikborsadiya/vali-admin#8]
hi pratikborsadiya,

In this image observe date picker is working. But i need date with time and seconds also.

![datetime](https://user-images.githubusercontent.com/24804092/31663105-8d52d216-b35e-11e7-9309-f6e7d3a224f3.png)

**Comment by pratikborsadiya** [comment]
@sanekiran The datepicker provided with the theme is from an external repo which is provided by https://github.com/uxsolutions/bootstrap-datepicker and it's not possible to select time with the datepicker. I suggest you to use this datetimepicker instead https://eonasdan.github.io/bootstrap-datetimepicker/.
