### ISSUE TITLE
Bootstrap Notify show full width on smartphone

### ISSUE THREAD

**Issue by anhchungite** [pratikborsadiya/vali-admin#88]
I think if Bootstrap Notify message have margin left and right it will more beautiful
![Screenshot_20190707-000816](https://user-images.githubusercontent.com/28822504/60759227-abfd3400-a04b-11e9-9112-9ca55ec780ef.jpg)

**Comment by pratikborsadiya** [comment]
Bootstrap Notify is not natively supported in the latest version.
