### ISSUE TITLE
Toggle Button does not start "on"

### ISSUE THREAD

**Issue by yardz** [pratikborsadiya/vali-admin#89]
**Describe the bug**
When I use toggle it always starts the page down.

**To Reproduce**
1. Go to **form-custom.html** (line 188)
2. insert ``value="true"`` on **input**
3. reload the page

**Expected behavior**
When input is active, start the page with toggl on.

**Comment by pratikborsadiya** [comment]
@yardz You should use checked attribute insted of value attribute on a checkbox input as per HTML standard. Use checked attribute and it will work.
