### ISSUE TITLE
grunt watch replace autoprefixer

### ISSUE THREAD

**Issue by juanjosezg** [pratikborsadiya/vali-admin#94]
i got this when i run grunt watch.

` grunt watch

  Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option cause some error. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
  https://github.com/browserslist/browserslist#readme
  https://twitter.com/browserslist`

**Comment by pratikborsadiya** [comment]
fixed in 44735d3d71d3e6bd448e27a39e4c188140b3c13c
